name: Generate JSON Files
on: [push, workflow_dispatch]

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate list.json
      run: |
        # 获取所有图片路径
        find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" \) \
          | grep -v -E '/\.|/functions/' \
          | sed 's|^\./||' \
          | jq -R -s 'split("\n") | map(select(. != ""))' > list.json
        
    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add list.json
        git diff --cached --quiet || git commit -m "更新图片列表"
        git push
