name: Generate list.json
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate list.json
        run: |
          find * -type f  $ -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.webp" -o -iname "*.gif" $ \
            | sort | jq -R -s -c 'split("\n")[:-1]' > list.json
      - name: Commit & Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add list.json
          git diff --cached --quiet || (git commit -m "chore: update list.json" && git push)
