name: Generate JSON Files
on: [push, workflow_dispatch]

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # 关键修复：启用写权限
        persist-credentials: true
        fetch-depth: 0
    
    - name: Install dependencies
      run: sudo apt-get install -y jq
    
    - name: Generate list.json
      run: |
        # 获取所有图片路径（排除.git目录和functions目录）
        find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" \) \
          | grep -v -E '/\.git/|/functions/' \
          | sed 's|^\./||' \
          | jq -R -s 'split("\n") | map(select(. != ""))' > list.json
        
        # 显示生成结果（调试用）
        cat list.json
        
    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add list.json
        
        # 检查是否有更改需要提交
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "自动更新图片列表 [skip ci]"
          git push
        fi
