name: Generate JSON Files
on: 
  push:
    paths:
      - '!list.json'  # 排除list.json本身的变化
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 关键修复：启用写权限和完整历史记录
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.ref }}
    
    - name: Install dependencies
      run: sudo apt-get install -y jq
    
    - name: Generate list.json
      run: |
        # 获取所有图片路径
        find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" \) \
          | grep -v -E '/\.git/|/functions/' \
          | sed 's|^\./||' \
          | jq -R -s 'split("\n") | map(select(. != ""))' > list.json
        
        # 显示生成结果
        echo "Generated list.json:"
        head list.json
        
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    
    - name: Commit and push changes
      run: |
        git add list.json
        if ! git diff-index --quiet HEAD --; then
          git commit -m "自动更新图片列表 [skip ci]"
          git pull --rebase  # 确保是最新代码
          git push origin HEAD:${{ github.ref }}
          echo "Changes pushed successfully"
        else
          echo "No changes to commit"
        fi
